// <auto-generated />
namespace Meu.Orcamento.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cria_banco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cria_banco));
        
        string IMigrationMetadata.Id
        {
            get { return "201802241819576_cria_banco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
